hosts:
  - host: 13.218.146.104
    user: ubuntu
    key_filename: ~/.ssh/yasir-aws-meril.pem
    name: web-app-03
  
  - host: 3.95.177.123
    user: ubuntu
    key_filename: ~/.ssh/yasir-aws-meril.pem
    name: web-app-02
  
  - host: 98.93.221.0
    user: ubuntu
    key_filename: ~/.ssh/yasir-aws-meril.pem
    name: web-app-01
